/*
 * generated by Xtext 2.30.0
 */
package vv.xtext.example.mydsl1.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractMyDslScopeProvider extends DelegatingScopeProvider {
}
