/**
 * generated by Xtext 2.30.0
 */
package org.xtext.example.mydsl.formatting2;

import com.google.inject.Inject;
import java.util.Arrays;
import org.eclipse.emf.common.util.EList;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.xtext.formatting2.AbstractFormatter2;
import org.eclipse.xtext.formatting2.IFormattableDocument;
import org.eclipse.xtext.resource.XtextResource;
import org.eclipse.xtext.xbase.lib.Extension;
import org.xtext.example.mydsl.myDsl.Mission;
import org.xtext.example.mydsl.myDsl.ProblemSpecification;
import org.xtext.example.mydsl.myDsl.QoS;
import org.xtext.example.mydsl.myDsl.Robot;
import org.xtext.example.mydsl.myDsl.RobotsModel;
import org.xtext.example.mydsl.myDsl.TasksModel;
import org.xtext.example.mydsl.myDsl.WorldModel;
import org.xtext.example.mydsl.services.MyDslGrammarAccess;

@SuppressWarnings("all")
public class MyDslFormatter extends AbstractFormatter2 {
  @Inject
  @Extension
  private MyDslGrammarAccess _myDslGrammarAccess;

  protected void _format(final ProblemSpecification problemSpecification, @Extension final IFormattableDocument document) {
    EList<WorldModel> _worldModel = problemSpecification.getWorldModel();
    for (final WorldModel worldModel : _worldModel) {
      document.<WorldModel>format(worldModel);
    }
    EList<TasksModel> _tasksModel = problemSpecification.getTasksModel();
    for (final TasksModel tasksModel : _tasksModel) {
      document.<TasksModel>format(tasksModel);
    }
    document.<RobotsModel>format(problemSpecification.getRobotsModel());
    EList<Mission> _mission = problemSpecification.getMission();
    for (final Mission mission : _mission) {
      document.<Mission>format(mission);
    }
    EList<QoS> _qos = problemSpecification.getQos();
    for (final QoS qoS : _qos) {
      document.<QoS>format(qoS);
    }
  }

  protected void _format(final RobotsModel robotsModel, @Extension final IFormattableDocument document) {
    EList<Robot> _robots = robotsModel.getRobots();
    for (final Robot robot : _robots) {
      document.<Robot>format(robot);
    }
  }

  public void format(final Object problemSpecification, final IFormattableDocument document) {
    if (problemSpecification instanceof XtextResource) {
      _format((XtextResource)problemSpecification, document);
      return;
    } else if (problemSpecification instanceof ProblemSpecification) {
      _format((ProblemSpecification)problemSpecification, document);
      return;
    } else if (problemSpecification instanceof RobotsModel) {
      _format((RobotsModel)problemSpecification, document);
      return;
    } else if (problemSpecification instanceof EObject) {
      _format((EObject)problemSpecification, document);
      return;
    } else if (problemSpecification == null) {
      _format((Void)null, document);
      return;
    } else if (problemSpecification != null) {
      _format(problemSpecification, document);
      return;
    } else {
      throw new IllegalArgumentException("Unhandled parameter types: " +
        Arrays.<Object>asList(problemSpecification, document).toString());
    }
  }
}
