/**
 * generated by Xtext 2.30.0
 */
package org.xtext.example.mydsl.myDsl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>All Robots X</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.myDsl.AllRobotsX#getCoordinate <em>Coordinate</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.AllRobotsX#getType <em>Type</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.AllRobotsX#getXy <em>Xy</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getAllRobotsX()
 * @model
 * @generated
 */
public interface AllRobotsX extends QoS
{
  /**
   * Returns the value of the '<em><b>Coordinate</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Coordinate</em>' attribute.
   * @see #setCoordinate(String)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getAllRobotsX_Coordinate()
   * @model
   * @generated
   */
  String getCoordinate();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.AllRobotsX#getCoordinate <em>Coordinate</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Coordinate</em>' attribute.
   * @see #getCoordinate()
   * @generated
   */
  void setCoordinate(String value);

  /**
   * Returns the value of the '<em><b>Type</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Type</em>' attribute.
   * @see #setType(String)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getAllRobotsX_Type()
   * @model
   * @generated
   */
  String getType();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.AllRobotsX#getType <em>Type</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Type</em>' attribute.
   * @see #getType()
   * @generated
   */
  void setType(String value);

  /**
   * Returns the value of the '<em><b>Xy</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Xy</em>' attribute.
   * @see #setXy(double)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getAllRobotsX_Xy()
   * @model
   * @generated
   */
  double getXy();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.AllRobotsX#getXy <em>Xy</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Xy</em>' attribute.
   * @see #getXy()
   * @generated
   */
  void setXy(double value);

} // AllRobotsX
