/**
 * generated by Xtext 2.30.0
 */
package org.xtext.example.mydsl.myDsl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>All Robots Deploy</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getAllRobotsDeploy()
 * @model
 * @generated
 */
public interface AllRobotsDeploy extends QoS
{
} // AllRobotsDeploy
