/**
 * generated by Xtext 2.30.0
 */
package org.xtext.example.mydsl.myDsl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Atomic Task</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.myDsl.AtomicTask#getRobots <em>Robots</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.AtomicTask#getLoc <em>Loc</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getAtomicTask()
 * @model
 * @generated
 */
public interface AtomicTask extends TasksModel
{
  /**
   * Returns the value of the '<em><b>Robots</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Robots</em>' attribute.
   * @see #setRobots(int)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getAtomicTask_Robots()
   * @model
   * @generated
   */
  int getRobots();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.AtomicTask#getRobots <em>Robots</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Robots</em>' attribute.
   * @see #getRobots()
   * @generated
   */
  void setRobots(int value);

  /**
   * Returns the value of the '<em><b>Loc</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Loc</em>' reference.
   * @see #setLoc(Location)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getAtomicTask_Loc()
   * @model
   * @generated
   */
  Location getLoc();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.AtomicTask#getLoc <em>Loc</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Loc</em>' reference.
   * @see #getLoc()
   * @generated
   */
  void setLoc(Location value);

} // AtomicTask
