/**
 * generated by Xtext 2.30.0
 */
package org.xtext.example.mydsl.myDsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Location Or Space</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.myDsl.LocationOrSpace#getSpace <em>Space</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.LocationOrSpace#getLoc <em>Loc</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getLocationOrSpace()
 * @model
 * @generated
 */
public interface LocationOrSpace extends EObject
{
  /**
   * Returns the value of the '<em><b>Space</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Space</em>' attribute.
   * @see #setSpace(String)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getLocationOrSpace_Space()
   * @model
   * @generated
   */
  String getSpace();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.LocationOrSpace#getSpace <em>Space</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Space</em>' attribute.
   * @see #getSpace()
   * @generated
   */
  void setSpace(String value);

  /**
   * Returns the value of the '<em><b>Loc</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Loc</em>' reference.
   * @see #setLoc(Location)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getLocationOrSpace_Loc()
   * @model
   * @generated
   */
  Location getLoc();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.LocationOrSpace#getLoc <em>Loc</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Loc</em>' reference.
   * @see #getLoc()
   * @generated
   */
  void setLoc(Location value);

} // LocationOrSpace
