/**
 * generated by Xtext 2.30.0
 */
package org.xtext.example.mydsl.myDsl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Robots X</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.myDsl.RobotsX#getRobot <em>Robot</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.RobotsX#getCoordinate <em>Coordinate</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.RobotsX#getType <em>Type</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.RobotsX#getXy <em>Xy</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getRobotsX()
 * @model
 * @generated
 */
public interface RobotsX extends QoS
{
  /**
   * Returns the value of the '<em><b>Robot</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Robot</em>' reference.
   * @see #setRobot(Robot)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getRobotsX_Robot()
   * @model
   * @generated
   */
  Robot getRobot();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.RobotsX#getRobot <em>Robot</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Robot</em>' reference.
   * @see #getRobot()
   * @generated
   */
  void setRobot(Robot value);

  /**
   * Returns the value of the '<em><b>Coordinate</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Coordinate</em>' attribute.
   * @see #setCoordinate(String)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getRobotsX_Coordinate()
   * @model
   * @generated
   */
  String getCoordinate();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.RobotsX#getCoordinate <em>Coordinate</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Coordinate</em>' attribute.
   * @see #getCoordinate()
   * @generated
   */
  void setCoordinate(String value);

  /**
   * Returns the value of the '<em><b>Type</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Type</em>' attribute.
   * @see #setType(String)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getRobotsX_Type()
   * @model
   * @generated
   */
  String getType();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.RobotsX#getType <em>Type</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Type</em>' attribute.
   * @see #getType()
   * @generated
   */
  void setType(String value);

  /**
   * Returns the value of the '<em><b>Xy</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Xy</em>' attribute.
   * @see #setXy(double)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getRobotsX_Xy()
   * @model
   * @generated
   */
  double getXy();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.RobotsX#getXy <em>Xy</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Xy</em>' attribute.
   * @see #getXy()
   * @generated
   */
  void setXy(double value);

} // RobotsX
