/**
 * generated by Xtext 2.30.0
 */
package org.xtext.example.mydsl.myDsl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Robots XX</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.myDsl.RobotsXX#getRobot <em>Robot</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.RobotsXX#getCoordinate <em>Coordinate</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.RobotsXX#getXy1 <em>Xy1</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.RobotsXX#getXy2 <em>Xy2</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getRobotsXX()
 * @model
 * @generated
 */
public interface RobotsXX extends QoS
{
  /**
   * Returns the value of the '<em><b>Robot</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Robot</em>' reference.
   * @see #setRobot(Robot)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getRobotsXX_Robot()
   * @model
   * @generated
   */
  Robot getRobot();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.RobotsXX#getRobot <em>Robot</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Robot</em>' reference.
   * @see #getRobot()
   * @generated
   */
  void setRobot(Robot value);

  /**
   * Returns the value of the '<em><b>Coordinate</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Coordinate</em>' attribute.
   * @see #setCoordinate(String)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getRobotsXX_Coordinate()
   * @model
   * @generated
   */
  String getCoordinate();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.RobotsXX#getCoordinate <em>Coordinate</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Coordinate</em>' attribute.
   * @see #getCoordinate()
   * @generated
   */
  void setCoordinate(String value);

  /**
   * Returns the value of the '<em><b>Xy1</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Xy1</em>' attribute.
   * @see #setXy1(double)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getRobotsXX_Xy1()
   * @model
   * @generated
   */
  double getXy1();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.RobotsXX#getXy1 <em>Xy1</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Xy1</em>' attribute.
   * @see #getXy1()
   * @generated
   */
  void setXy1(double value);

  /**
   * Returns the value of the '<em><b>Xy2</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Xy2</em>' attribute.
   * @see #setXy2(double)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getRobotsXX_Xy2()
   * @model
   * @generated
   */
  double getXy2();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.RobotsXX#getXy2 <em>Xy2</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Xy2</em>' attribute.
   * @see #getXy2()
   * @generated
   */
  void setXy2(double value);

} // RobotsXX
