/**
 * Github version v1: https://github.com/Gricel-lee/Kanoa/blob/main/Resources/src/1%20DSL%20Generation/code/org.xtext.example.mydsl/bin/org/xtext/example/mydsl/generator/MyDslGenerator.xtend
 * generated by Xtext 2.30.0
 */
package org.xtext.example.mydsl.generator;

import org.eclipse.emf.ecore.resource.Resource;
import org.eclipse.xtext.generator.AbstractGenerator;
import org.eclipse.xtext.generator.IFileSystemAccess2;
import org.eclipse.xtext.generator.IGeneratorContext;
import org.eclipse.xtext.xbase.lib.InputOutput;

/**
 * Global Variables
 */
@SuppressWarnings("all")
public class MyDslGenerator extends AbstractGenerator {
  private Tree tree;

  @Override
  public void doGenerate(final Resource resource, final IFileSystemAccess2 fsa, final IGeneratorContext context) {
    InputOutput.<String>println("\nStarting generator");
    Tree _tree = new Tree();
    this.tree = _tree;
    this.tree.createTree(resource, fsa);
    this.tree.generateTreeFile("modelMissionsTree.txt");
    AlloyFile.createAlloyFile(this.tree, resource);
  }
}
