/**
 * generated by Xtext 2.30.0
 */
package org.xtext.example.mydsl.myDsl.impl;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.xtext.example.mydsl.myDsl.MyDslPackage;
import org.xtext.example.mydsl.myDsl.WorldModel;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>World Model</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class WorldModelImpl extends MinimalEObjectImpl.Container implements WorldModel
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected WorldModelImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return MyDslPackage.Literals.WORLD_MODEL;
  }

} //WorldModelImpl
